#!/bin/bash

# Get the list of paths using ls command
paths=$(ls -lrt -d -1 "$PWD"/{*,.png})

# Loop through each path
for path in $paths; do
    # Apply fyne bundle command
    fyne bundle -o bundled.go --append "$path"
done